# Generated by Django 5.0.7 on 2024-07-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='surname',
            field=models.CharField(default='surname', max_length=100),
            preserve_default=False,
        ),
    ]
