# Generated by Django 5.0.7 on 2024-07-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_jobses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('old_work', models.CharField(max_length=100)),
                ('busyness', models.CharField(max_length=100)),
                ('chart', models.CharField(max_length=100)),
                ('remote_work', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False)),
                ('underworking', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False)),
                ('table', models.TextField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Jobses',
        ),
    ]
