# Generated by Django 5.0.7 on 2024-07-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_jobs_delete_jobses'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='gorod',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
