# Generated by Django 5.0.7 on 2024-07-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_jobs_gorod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='gorod',
            field=models.CharField(max_length=100),
        ),
    ]
