# Generated by Django 5.0.7 on 2024-07-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_jobs_gorod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='busyness',
            new_name='grafik',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='table',
            new_name='kratkoye_opisaniye',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='chart',
            new_name='trebuyemyy_opyt_raboty',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='remote_work',
            new_name='udalonnayarabota',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='description',
            new_name='usloviya',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='gorod',
            new_name='zanyatost',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='old_work',
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='underworking',
        ),
        migrations.AddField(
            model_name='jobs',
            name='mesto_raboty',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='jobs',
            name='obyazannosti',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='opisaniye',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='trebovaniya',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
