# Generated by Django 5.0.7 on 2024-08-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='opisaniye',
        ),
    ]
