# Generated by Django 5.1 on 2024-08-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_object_is_ready'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
