# Generated by Django 5.1 on 2024-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='job_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
