# Generated by Django 5.1 on 2024-08-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_applicant_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='additional_images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
