# Generated by Django 5.1 on 2024-08-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_object_image1_object_image2_object_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='image1',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image2',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image3',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image4',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image5',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image6',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image7',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
    ]
