# Generated by Django 5.1 on 2024-08-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_object_image1_alter_object_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='image10',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image11',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image12',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image13',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image14',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image15',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image16',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image17',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image18',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image19',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image20',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image21',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image22',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image23',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image24',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image25',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image26',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image27',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image28',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image29',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image30',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image31',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image32',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image33',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image34',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image35',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image36',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image37',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image38',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image39',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image40',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image41',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image42',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image43',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image44',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image45',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image46',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image47',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image48',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image49',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image50',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image51',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image52',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image53',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image54',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image55',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image56',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image57',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image58',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image59',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image60',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image61',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image62',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image63',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image64',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image65',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image66',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image67',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image68',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image69',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image70',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image71',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image72',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image73',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image74',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image75',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image76',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image77',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image78',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image79',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image8',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image80',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
        migrations.AddField(
            model_name='object',
            name='image9',
            field=models.ImageField(default='path/image.jpeg', upload_to='objectImg/'),
        ),
    ]
