# Generated by Django 5.1 on 2024-08-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_object_description_alter_object_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image7',
            field=models.ImageField(blank=True, null=True, upload_to='objectImg/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='image8',
            field=models.ImageField(blank=True, null=True, upload_to='objectImg/'),
        ),
    ]
