# Generated by Django 5.1 on 2024-08-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_object_image1_alter_object_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectmain',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
