# Generated by Django 5.1 on 2024-08-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_objectmain_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmain',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
