# Generated by Django 5.1 on 2024-08-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_objectmain_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectmain',
            name='date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
